import {
  OmmlAcc,
  OmmlAccpr,
  OmmlBar,
  OmmlBarpr,
  OmmlBorderbox,
  OmmlBorderboxpr,
  OmmlBox,
  OmmlBoxpr,
  OmmlD,
  OmmlDpr,
  OmmlElement,
  OmmlEqarr,
  OmmlEqarrpr,
  OmmlF,
  OmmlFpr,
  OmmlFunc,
  OmmlFuncpr,
  OmmlGroupchr,
  OmmlGroupchrpr,
  OmmlLimlow,
  OmmlLimlowpr,
  OmmlLimupp,
  OmmlLimupppr,
  OmmlM,
  OmmlMc,
  OmmlMcpr,
  OmmlMcs,
  OmmlMpr,
  OmmlMr,
  OmmlNary,
  OmmlNarypr,
  OmmlOmath,
  OmmlPhant,
  OmmlPhantpr,
  OmmlR,
  OmmlRad,
  OmmlRadpr,
  OmmlRpr,
  OmmlSpre,
  OmmlSprepr,
  OmmlSsub,
  OmmlSsubpr,
  OmmlSsubsup,
  OmmlSsubsuppr,
  OmmlSsup,
  OmmlSsuppr,
  OmmlT,
} from "./model.ts";

export default function domToOmml(el: Element): OmmlElement | undefined {
  return toOmmlTable[el.tagName as keyof typeof toOmmlTable]?.(el);
}

const todo = () => undefined;
const toOmmlTable: {
  [tagName in OmmlElement["tagName"]]: (
    el: Element,
  ) => Extract<OmmlElement, { tagName: tagName }> | undefined;
} = {
  "m:oMath": todo,
  "m:acc": todo,
  "m:bar": todo,
  "m:box": todo,
  "m:borderBox": todo,
  "m:d": todo,
  "m:eqArr": todo,
  "m:f": todo,
  "m:func": todo,
  "m:groupChr": todo,
  "m:limLow": todo,
  "m:limUpp": todo,
  "m:m": todo,
  "m:nary": todo,
  "m:phant": todo,
  "m:rad": todo,
  "m:sPre": todo,
  "m:sSub": todo,
  "m:sSubSup": todo,
  "m:sSup": todo,
  "m:r": todo,
  "m:rPr": todo,
  "m:t": todo,
  "m:accPr": todo,
  "m:barPr": todo,
  "m:boxPr": todo,
  "m:borderBoxPr": todo,
  "m:dPr": todo,
  "m:eqArrPr": todo,
  "m:fPr": todo,
  "m:funcPr": todo,
  "m:groupChrPr": todo,
  "m:limLowPr": todo,
  "m:limUppPr": todo,
  "m:mPr": todo,
  "m:mr": todo,
  "m:mcs": todo,
  "m:mc": todo,
  "m:mcPr": todo,
  "m:naryPr": todo,
  "m:phantPr": todo,
  "m:radPr": todo,
  "m:sPrePr": todo,
  "m:sSubPr": todo,
  "m:sSubSupPr": todo,
  "m:sSupPr": todo,
};
